
sqlcmd -S DEV\DEV -i spAPQ_Create_Availability.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_AvailabilityByArea.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_AvailabilityByLine.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_AvailabilitySummary.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_Counts.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_CountsByArea.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_CountsByEquipment.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_CountsByLine.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_CountsSummary.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_Equipment.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_EquipmentByArea.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_EquipmentByLine.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_EquipmentSummary.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_ProdTimes.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_ProdTimesByArea.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_ProdTimesByEquipment.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_ProdTimesByLine.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_ProdTimesSummary.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_SetupAndStart.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_SetupAndStartByArea.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_SetupAndStartByEquipment.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_SetupAndStartByLine.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_SetupAndStartSummary.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_Stops.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_StopsByArea.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_StopsByEquipment.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_StopsByLine.sql
sqlcmd -S DEV\DEV -i spAPQ_Create_StopsSummary.sql
sqlcmd -S DEV\DEV -i spAPQ_Execute_Runtime.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_APQ.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_APQByArea.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_APQByEquipment.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_APQByLine.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_Availability.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_Counts.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_Equipment.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_ProdTimes.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_SetupAndStarts.sql
sqlcmd -S DEV\DEV -i spAPQ_Rpt_Stops.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_Availability.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_AvailabilityByArea.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_AvailabilityByEquipment.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_AvailabilityByLine.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_Counts.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_CountsByArea.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_CountsByEquipment.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_CountsByLine.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_DataChart.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_DataChartByArea.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_DataChartByEquipment.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_DataChartByLine.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_Index.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_IndexByArea.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_IndexByEquipment.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_IndexByLine.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_ProductionSchedule.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_ProductionScheduleByArea.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_ProductionScheduleByEquipment.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_ProductionScheduleByLine.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_Stops.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_StopsByArea.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_StopsByEquipment.sql
sqlcmd -S DEV\DEV -i v_APQ_Get_StopsByLine.sql

